# Generated by Django 2.1.7 on 2019-02-23 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('character_health', models.IntegerField()),
                ('character_level', models.IntegerField()),
                ('character_armor_class', models.IntegerField()),
                ('character_initiative', models.IntegerField(null=True)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='creatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creature_name', models.CharField(max_length=50)),
                ('creature_health', models.IntegerField()),
                ('creature_level', models.IntegerField()),
                ('creature_armor_class', models.IntegerField()),
                ('creature_initiative', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dm_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='extended_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pc', models.BooleanField()),
                ('is_dm', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='creatures',
            name='dm_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DIT.dm_session'),
        ),
    ]
