# Generated by Django 2.1.7 on 2019-02-24 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_users',
            name='dm_session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DIT.dm_session'),
        ),
        migrations.AlterField(
            model_name='dm_session',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
