# Generated by Django 2.1.7 on 2019-02-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DIT', '0002_auto_20190224_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm_session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
